source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/MooYooOrg/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'KingfisherWebP_Tests' do
  pod 'KingfisherWebP', :path => '../'
end
