name: deploy to cocoapods

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          export LIB_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          gem install cocoapods
          pod setup
          perl -i -pe 'if (/^(\s*)def validated\?/) { $_ .= "${1}  return true\n" }' "$(gem which cocoapods/validator)"
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        shell: bash
