name: unittest

on: [push, pull_request]

jobs:
  run-test:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: [
          'macOS',
          'iOS Simulator,OS=latest',
          'tvOS Simulator,OS=latest',
          'watchOS Simulator,OS=latest'
        ]
        swift-version: [5.0]
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        env:
          DESTINATION: platform=${{ matrix.destination }}
          SWIFT_VERSION: ${{ matrix.swift-version }}
        run: |
          xcodebuild clean test -project KingfisherWebP.xcodeproj -scheme KingfisherWebP -destination "${DESTINATION}"
