name: unittest

on: [push, pull_request]

jobs:
  run-test:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: [
          'macOS', 
          'iOS Simulator,name=iPhone 16', 
          'tvOS Simulator,name=Apple TV 4K (3rd generation)', 
          'watchOS Simulator,name=Apple Watch Series 11 (46mm)'
        ]
        swift-version: [5.0]
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        env:
          DESTINATION: platform=${{ matrix.destination }}
          SWIFT_VERSION: ${{ matrix.swift-version }}
        run: |
          xcodebuild clean test -project KingfisherWebP.xcodeproj -scheme KingfisherWebP -destination "${DESTINATION}"
